export const LOCATIONSEARCH = "LOCATIONSEARCH";
export const JOBSEARCH = "JOBSEARCH";
export const CLICK = "CLICK";

export const REQUESTS = {
  FETCH_POSTS_PENDING: "FETCH_POSTS_PENDING",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
};
